feature: #33 | Add DockerFile and feature: #34Rename the users_servic…
ShivamNagpal/users-service pull request #47
Opened 2024-02-03 19:34 UTC by astha-singh-2445

…e to users-service in the settings.gradle.kts and the group name in the build.gradle.kts

2024-02-04 13:02 UTC, ShivamNagpal requested changes

2024-02-04 13:02 UTC, ShivamNagpal commented on Dockerfile
> +RUN ./gradlew clean assemble
It should be `./gradlew clean build`

2024-02-04 13:02 UTC, ShivamNagpal commented on Dockerfile
> +COPY settings.gradle.kts settings.gradle.kts
Copy everything else except src and then put `RUN ./gradlew check --dry-run` and then copy src to allow caching of the Gradle dependencies

2024-02-04 13:02 UTC, ShivamNagpal commented on Dockerfile
> +ARG AUTH_TOKEN_PRIVATE_KEY
Remove all the args and env from the Builder phase, as they are not needed

2024-02-04 18:14 UTC, ShivamNagpal commented on Dockerfile
> +RUN ./gradlew clean assemble
Once you do this, you will require to copy the spotless.xml as well, otherwise the build will fail because of file linking issues

2024-02-05 06:55 UTC, astha-singh-2445 commented on Dockerfile
> +RUN ./gradlew clean assemble
fixed

2024-02-07 14:56 UTC, ShivamNagpal approved these changes

2024-02-07 14:57 UTC, merged